# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.tx ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . /app

# Patch server to bind to all interfaces, dynamic port, and serve at root
RUN sed -i 's/host="127.0.0.1"/host=os.getenv("HOST", "0.0.0.0")/' server.py \
    && sed -i 's/port=8000/port=int(os.getenv("PORT", str(8000)))/' server.py \
    && sed -i 's|path="/mcp"|path="/"|' server.py

# Expose default port
EXPOSE 8000

# Start the server
CMD ["python", "server.py"]
